version: "3.9"

services:
  jenkins:
    image: jenkins/jenkins:lts
    ports:
      - 8081:8080
      - 50001:50000
    container_name: jenkins
    user: 0:0
    volumes:
    - ./jenkins_data:/var/jenkins_home