version: "3.9"

services:
  jenkins:
    build: ./
    #image: jenkins/jenkins:lts
    ports:
      - 8080:8080
      - 50000:50000
    container_name: jenkins
    user: 0:0
    volumes:
    - ./jenkins_data:/var/jenkins_home
    - /var/run/docker.sock:/var/run/docker.sock
    - /usr/bin/docker:/usr/bin/docker